### ISSUE TITLE
How can I get the results in the video you gave?

### ISSUE THREAD

**Issue by 834810071** [vcg-uvic/sportsfield_release#2]
How can I get the results in the video you gave?

**Comment by jiangwei221** [comment]
Lol, you can try the ipython notebook, there is a part for estimating homography for a short video(1 or 2 second). To get the results in the video, you need to manually split the cuts, run the estimation for every cut, then stitch them together.
There are some existing tools: https://pyscenedetect.readthedocs.io/en/latest/
The reason is that we want to keep the temporal smoothness.
